# Generated by Django 4.2.3 on 2023-08-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creaciones_multicolor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cumpleaños',
            new_name='cumpleanos',
        ),
    ]
